package:
  name: synth-voice
  version: 1.0

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  
  

requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  # build:
  #   - {{ compilers('c') }}
  host:
    - python=3.7
    - pip
  run:
    - python=3.7
    - librosa=0.9.0
    - cudatoolkit=11.3
    - pytorch=1.10.2
    - tensorflow<=1.15
    - unidecode    
    - inflect
    - tensorflow-estimator<=1.15.1
    

